### ISSUE TITLE
Why the SDK does not provide a way to fetch Long value?

### ISSUE THREAD

**Issue by apulbere** [open-feature/java-sdk#501]
I see we have getDoubleValue and getIntegerValue, but not for Long type.
I can open a PR to add that.

**Comment by Kavindu-Dodan** [comment]
@apulbere thank you for raising your concern. 

From your description, I assume you are referring to the feature flag evaluation contract [1]. I am not sure about the historical reason for ignoring the `Long` type. However, it could be a valuable addition for providers. 

From the spec point of view, we only enforce `number` evaluation [2]. When it comes to implementation, this translates into language-specific representations. 

Maybe we could aim for a generic representation of numbers via Java `Number` [3] type evaluation instead of supporting each sub-type of `Number` such as `Long` and `Short` 🤔 

cc - @toddbaert @justinabrahms appreciate opnion here

[1] - https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/FeatureProvider.java#L16-L24
[2] - https://github.com/open-feature/spec/blob/main/specification/sections/01-flag-evaluation.md#13-flag-evaluation
[3] - https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html

**Comment by aepfli** [comment]
I like this idea :) I also like Todd's suggestion to maintain backward compatibility. 

IMHO: we should 
- add `NumberEvaluation` as a default method to the interface and redirect it per default to the `DoubleEvaluation` (this way, we won't break existing providers)
- Now, my question would be if we deprecate the existing ones or want to keep them in place with a default implementation pointing to `NumberEvaluation` (I know a possible circular call if both are not implemented).

This ticket has been open for quite a while, and I think we should continue with this improvement. So, what do you think? especially about having default methods for all kinds of number sub-types or not.

**Comment by toddbaert** [comment]
I like your plan. I'm really not sure about your question though. My gut says deprecate the other numerics, but I'm not sure. 🤔

**Comment by aepfli** [comment]
relates to https://github.com/open-feature/java-sdk/issues/872

**Comment by carla-was-not-available** [comment]
Hey, I would love to work on this. :)

**Comment by chrfwow** [comment]
@carla-was-not-available are you still working on this?

**Comment by carla-was-not-available** [comment]
Hey. I've spent some time on this but got stuck, unfortunately. I'm going to unassign myself so someone else can take over. Sorry about that!

**Comment by chrfwow** [comment]
no problem

**Comment by toddbaert** [comment]
This was revived based on a slack thread: https://cloud-native.slack.com/archives/C03J36ZP020/p1779268348946649

@NeaguGeorgiana23 :

hey, I noticed an inconsistency in how integer flags are handled in the Java implementation (specifically in the Evaluator interface and related testkit) compared to how floating-point numbers are handled, and how other language SDKs handle integers.

The problem is that float flags are mapped to Double, while integer flags are mapped to Integer. This allows float flags to handle 64-bit floating-point numbers while integer flags can only handle 32-bit signed integer numbers.

This problem comes from the following implementation:

In the dev.openfeature.contrib.tools.flagd.api.Evaluator interface (and its usage in EvaluationSteps.java ), we have the following method signatures:
// From Evaluator.java
ProviderEvaluation<Integer> resolveIntegerValue(String flagKey, Integer defaultValue, EvaluationContext ctx);
ProviderEvaluation<Double> resolveDoubleValue(String flagKey, Double defaultValue, EvaluationContext ctx);

And in EvaluationSteps.java, the evaluation is handled as follows:

```java
// From EvaluationSteps.java

case integer:
state.evaluation = state.getEvaluator().resolveIntegerValue(state.flagKey, (Integer) state.defaultValue, state.context);
  break;

case float:
  state.evaluation = state.getEvaluator().resolveDoubleValue(state.flagKey, (Double) state.defaultValue, state.context);
  break;
```
This creates two main issues:

Internal Inconsistency: While we provide 64-bit precision for floating-point numbers by using Double, we restrict integers to 32-bit by using Integer instead of Long (64-bit).
Cross-Language Inconsistency: Other OpenFeature SDKs and flagd implementations handle integers as 64-bit numbers to avoid overflow issues and ensure a wide range of values can be supported (for reference: go uses int64, C++ typically uses 64-bit integers and Python handles integers with arbitrary precision, which is 64-bit or more in this context).
This discrepancy means that a flag configuration using large integer values might work perfectly fine in a Go or Python service but could cause overflow or type-mismatch issues in a Java service using the same flag definition.

Proposed Solution
Should we consider updating the Java API to use Long for integer flag resolution to align with the 64-bit standard used in other languages and to be consistent with the 64-bit precision we give to floats?

As an example, if we have a gherkin scenario like this one:
```
Scenario Outline: Fractional operator with float mapping
    Given a String-flag with key "fractional-basic-flag" and a fallback value "fallback"
    And a context containing a key "hashing_input", with type "<type>" and with value "<hashing_input>"
    When the flag was evaluated with details
    Then the resolved details value should be "<value>"

    Examples:
      | hashing_input         | type    | value    |
      | 1.0                   | Float   | bucket23 |
      | 1                     | Integer | bucket23 |
      | 1.0000000000000001    | Float   | bucket23 |
      | -2.0                  | Float   | bucket12 |
      | -2                    | Integer | bucket12 |
      | 9007199254740992.0    | Float   | bucket10 |
      | 9007199254740992      | Integer | bucket10 |
```

Java outputs the following error:

```
[ERROR] dev.openfeature.contrib.tools.flagd.core.e2e.FlagdCoreEvaluatorTest.Example #1.7 -- Time elapsed: 0.021 s <<< ERROR!
java.lang.NumberFormatException: For input string: "9007199254740992"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:527)
at java.base/java.lang.Integer.parseInt(Integer.java:624)
```

While Go and Python have no problems passing this scenario.

**Comment by toddbaert** [comment]
If everyone agrees I will update this issue with the below:

---

## Problem

The Java SDK's integer flag accessor returns `Integer` (32-bit, max ~2.1B). Flag values above `Integer.MAX_VALUE` cannot be represented. This shows up in real workloads; for example, any current Unix epoch in milliseconds (`1748000000000`, ~1.7 trillion) or a byte-size threshold above ~2.1 GB (`5000000000` for a 5 GB cap) is well past the 32-bit ceiling (we ran into this one at Dynatrace).

## Proposal

Add `Long` flag accessors alongside the existing `Integer` ones:

- Client: `getLongValue(...)` / `getLongDetails(...)`
- Provider: `FeatureProvider.getLongEvaluation(...)`
- New `FlagValueType.LONG`

Typed `Long` (not a generic `Number` accessor).

## Justifications

- Matches Java idioms (`ResultSet.getLong`, `JsonNode.asLong`).
- Preserves static type safety; no caller-side subtype interrogation needed.
- Consistent with existing typed accessors (`Integer`, `Double`, `Boolean`, `String`).
- `getObjectValue` already covers schemaless cases.

## Migration (non-breaking)

`FeatureProvider.getLongEvaluation` ships with a default implementation that widens from `getIntegerEvaluation` (this is lossless). Existing providers compile and run unchanged. Providers opt into native 64-bit support by overriding the method when their backend or wire-format supports it (flagd protobuf `int64`, OFREP JSON with `Long`-preserving parsers, etc.).

| Audience | Action required |
| --- | --- |
| End users | None; new methods are additive |
| Existing providers | None; default impl widens from `Integer` |
| Providers wanting native 64-bit | Override `getLongEvaluation` |

## Notes

Java and .NET are bounded by 32-bit integers; JS/TS is bounded by IEEE-754's 2^53 safe-integer ceiling. Go (int64) and Python (arbitrary precision) are unaffected. Parallel proposals in dotnet-sdk would bring the ecosystem closer to parity.

The OpenFeature spec is currently silent on integer precision, which is why SDKs have drifted to different ceilings. A natural floor:

> **Requirement (proposed)**: SDKs whose host language provides a native integer type capable of representing values in `[-(2^53 - 1), 2^53 - 1]` MUST expose a typed integer accessor that supports this range without precision loss.

_The range mirrors the interoperable integer range guaranteed by JSON (RFC 8259.6) and is the highest floor achievable end-to-end across common wire formats; a 2^63 floor would promise precision many transports can't deliver. Perhaps worth filing as a separate spec issue; the Java work here doesn't depend on it._

## Out of scope

- Wire-format precision end-to-end (provider/transport concern).
- Arbitrary-precision / `BigInteger` support.
- .NET implementation (same concerns)

**Comment by dd-oleksii** [comment]
Kotlin has recently [received Long support](https://github.com/open-feature/kotlin-sdk/pull/225). We tried widening default implementation of `getLongEvaluation` initially but eventually decided against it. The main issue is that it needs to pass through the default value to `getIntEvaluation` and this requires narrowing from `Long` to `Int` which may lead to truncation. It is possible to check that narrowing will be non-truncating but this may lead to surprises if users tries a high default value.

A default implementation returning an error is also perfectly backward-compatible.

I would also argue against defining integer ranges or narrowing promised range. Mostly because it seems arbitrary and incidental to OpenFeature SDKs — it's all controlled by providers and there's no place in SDKs that would prevent 2^63 from working.

The higher values are only an issue for JSON and only for JS — i.e. exactly the language that doesn't need `getLong`. Even then, there are ways to pass precise integers through JSON. So the issue is not widespread. (And to be pedantic, RFC 8259.6 _does not_ guarantee a safe integer range.)

My take is that this is already covered under [Conditional Requirement 1.3.3.1](https://openfeature.dev/specification/sections/flag-evaluation#conditional-requirement-1331):
> The client **SHOULD** provide functions for floating-point numbers and integers, consistent with language idioms.
> ```java
> int getIntValue(String flag, int defaultValue);
>
> long getFloatValue(String flag, long defaultValue);
> ```

Perhaps we should update the example to remind that `Long` is a possibility: https://github.com/open-feature/spec/pull/387. (It looks like we had int64/float64 [initially](https://github.com/open-feature/spec/pull/116) but it got accidentally corrupted [here](https://github.com/open-feature/spec/pull/179).)

**Comment by toddbaert** [comment]
> The main issue is that it needs to pass through the default value to getIntEvaluation and this requires narrowing from Long to Int which may lead to truncation

Yes, this is something I was worried about as well, and I think it's a valid concern. I agree it's risky. There's similar risk in adding a new getLong API method that no/few providers implement though. In fact, based on how few SDKs out there have long support, I'd worry that very few will support it at all and then you would get lots of defaulting here. Overall the situation is different in Java where we already have lots of providers that will be missing this method.

I can go either way, I guess I'm interested in more opinions.

**Comment by kinyoklion** [comment]
We also need to consider the Value/Structure types as you would similarly want the ability to get longs out of them/into them. 

I would say that getObjectValue would also be a better backing method than getIntegerValue, but unfortunately it would change the semantics for the provider in the value of type mismatches. So that probably isn't viable.

For example, with the LaunchDarly provider, I think that would get you (2^53)-1 without any provider changes (we would put the double into the value and it would get basically cast on the way out). Though it would have to obviously narrow for providers which are setting integers directly into the values, which would have been a problem for any provider which had true 64-bit types already.

**Comment by toddbaert** [comment]
@erka also brought up that the openfeature CLI might have issues generating Java code with this: https://cloud-native.slack.com/archives/C0344AANLA1/p1779809278908259?thread_ts=1779737896.685529&cid=C0344AANLA1

**Comment by nicklasl** [comment]
I think it is reasonable to support Longs, no doubt there. We've heard it from customers of the Confidence SDKs as well.

I am very much on the fence of adding the default implementation of the `FeatureProvider. getLongEvaluation` that is using `getIntegerEvaluation` though. I don't think it is up to the SDK to make that decision but rather leave that to provider authors. This aligns with how we thought about it when adding Long support in the Kotlin SDK (I see how breaking the `FeatureProvider` API here feel more painful since we are post 1.0).

A default implementation that throws sounds tempting but I also see the issue with provider authors not realizing there's a new method to implement, end/sdk users would only discover the gap at runtime, which isn't great either, BUT it would push provider authors to implement the functionality based on the signals they listen to the most :).

I don't think there's a perfect answer here for post 1.0 SDKs. But if I had to pick, I'd lean toward the throwing + default value over the widening one. The widening default has the SDK silently narrowing the Long default value to Int before passing it to the provider, that'll produce bugs that are only found when integer numbers are large enough, a bit nasty. At least a clear error tells the user "this provider doesn't support Long yet" rather than quietly truncating.

On the spec side, I agree with @dd-oleksii that the spec already somewhat covers this: the client SHOULD provide functions "consistent with language idioms." Long is idiomatic Java, just like int64 is idiomatic Go. I'm open to making that more clear though.

**Comment by lukas-reining** [comment]
> My take is that this is already covered under [Conditional Requirement 1.3.3.1](https://openfeature.dev/specification/sections/flag-evaluation#conditional-requirement-1331):

I agree, I think the spec defines what is needed already good enough, changing the example makes sense to me. 

> A default implementation that throws sounds tempting but I also see the issue with provider authors not realizing there's a new method to implement, end/sdk users would only discover the gap at runtime, which isn't great either, BUT it would push provider authors to implement the functionality based on the signals they listen to the most :).

I agree with this @nicklasl! I fear that the `getLongValue` would error in many providers for a long time which could be even more confusing for app authors than the default implementation. This also with what @toddbaert says: 

> In fact, based on how few SDKs out there have long support, I'd worry that very few will support it at all and then you would get lots of defaulting here

> For example, with the LaunchDarly provider, I think that would get you (2^53)-1 without any provider changes (we would put the double into the value and it would get basically cast on the way out). Though it would have to obviously narrow for providers which are setting integers directly into the values, which would have been a problem for any provider which had true 64-bit types already.

> I would say that getObjectValue would also be a better backing method than getIntegerValue, but unfortunately it would change the semantics for the provider in the value of type mismatches. So that probably isn't viable.

I think passing the long into the getIntegerValue in the default implementation as @toddbaert proposes seems like the most viable solution. 
When the default implementation is in use and a value larger than `Integer.MAX_VALUE` is passed to `getLongValue` we should at least log that this may lead to issues as the value is being floored.

**Comment by toddbaert** [comment]
I think based on everything above, there seems to be an ideal solution.

Premise 1: defaulting due to unimplemented methods is bad
Premise 2: truncating the default silently is bad
Premise 3: all ints can be widened to longs safely

Conclusion:

We should _attempt_ to delegate to the `getInt` method(s), throwing and logging only if the supplied long default is out of the int range.

This seems like the best of both worlds; we throw less than we would if we hand't implemented anything, and we resolve some value at least in most cases. We may want to warn either way when this happens, or at least warn on the first time such an evaluation is attempted. There's an another case here as well where the "backend" is storing longs but the associated provider doesn't support the retrial of longs. IMO, this is a situation where the provider is falling short of the contract of it's own system, and it should simply implement `getLong`, so I don't think it's something we have to worry about too much. Hopefully such providers will be enhanced quickly.

What do you all think?

I should mention, there's a similar conversation in flagd to officially limit numeric values to (2^53)-1, due to problems with parsing and JS handling. This number is bigger than a Java int, but smaller than a Java long.

**Comment by lukas-reining** [comment]
> We should attempt to delegate to the getInt method(s), throwing and logging only if the supplied long default is out of the int range.

I agree. It is a compromise but makes the current problem visible which I find is a real improvement. 

> What do you all think?

I support this way forward @toddbaert!

**Comment by chrfwow** [comment]
Why don't we delegate to `getDouble`? This gives us an even greater range of supported values before we'd have to throw

**Comment by toddbaert** [comment]
> Why don't we delegate to `getDouble`? This gives us an even greater range of supported values before we'd have to throw

@chrfwow 

I think you are right... Check my logic then... in that case my proposal becomes:

> We should attempt to delegate to the getDouble method(s), throwing and logging only if the supplied long default is beyond (2^53) -1.

I guess one caveat here is what to do if the `getDouble` value is a non-integer less than (2^53)-1... we've let providers decide to round or not in general for such questions, but in this case the SDK would have to make a call... throw? Round?

**Comment by chrfwow** [comment]
We should not deliver random values to users. If we can't seliver the value from the management system, we should throw instead of rounding

**Comment by nicklasl** [comment]
> What do you all think?

I can get behind this. Pragmatic 👍

**Comment by kinyoklion** [comment]
There could be some problems with providers that internally store flag representations more strongly typed. Such that if the storage is an integer than it cannot be accessed as a double.

Probably this would also affect 32/64 bit representations. 

I think that the in-memory provider for Java is one such provider: https://github.com/open-feature/java-sdk/blob/5562cb93fc8e769ed1b2800f8e6ceece3baaab4e/src/main/java/dev/openfeature/sdk/providers/memory/InMemoryProvider.java#L164

I think that that flagd RPC resolver would similarly produce a type mismatch error when the double variation method is used to resolve an integer.

Not insurmountable, but we will want to determine if you can coerce a 32-bit integer to a 64-bit one and if you can coerce a safe double to either of the integer types.

**Comment by toddbaert** [comment]
> I think that that flagd RPC resolver would similarly produce a type mismatch error when the double variation method is used to resolve an integer.

flagd has some specific inconsistencies around numeric conversion, but they're somewhat separate from this discussion; I'll file those independently. 

Proposing: add getLongValue with a default getLongEvaluation that delegates to getDoubleEvaluation, throwing on out-of-safe-range or fractional values. At the end of the day this is best-effort; providers can opt into whatever getLong implementation they feel is right, or leave it unimplemented. That said, @kinyoklion's observation is valid, and we may want to specify the expected coercion behavior here and update the in-memory provider's type-checking along with this change. It will take some time for consumers to start using this anyway.
